### ISSUE TITLE
Intern TypeError on running Intern with Node 0.10.x when specifying loaderOptions

### ISSUE THREAD

**Issue by dylans** [theintern/intern#489]
Our instructions state that Intern works with Node 0.10.x+ , but in my testing, it looks like it only works with 0.12.x and higher. In 0.10.x, I get the following error when running intern-client or intern-runner:

```
TypeError: undefined is not a function
  at <node_modules/intern/lib/executors/PreExecutor.js:202:15>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:330:15>
```

**Comment by vladikoff** [comment]
We use Intern 3.0.0 on 0.10 everyday (our stuff is not 0.12 ready yet), so probably need more details about your setup or trace it with a debugger

**Comment by dylans** [comment]
npm install intern
node 0.10.x
mac yosemite
Separately confirmed by another engineer on the sitepen team...

**Comment by vladikoff** [comment]
> node 0.10.x
mac yosemite

Yeah that's what we use on our dev machines and it's been fine. Really needs more info about the project or config setup.

**Comment by dylans** [comment]
fwiw, the config is rather stock/basic:

```
define([ 'intern/dojo/has' ], function (has) {
	return {
		proxyPort: 9000,
		proxyUrl: 'http://localhost:9000/',
		capabilities: {
			'selenium-version': '2.45.0'
		},
		environments: [
			{ browserName: 'chrome' }
		],
		maxConcurrency: 3,
		tunnel: 'NullTunnel',
		loaderOptions: {
			baseUrl: 'slides/internIntro',
			packages: [ { name: 'app', location: 'activity/workspace' } ]
		},
		suites: [ 'app/unit' ],
		functionalSuites: [ 'app/functional' ],
		excludeInstrumentation: /(?:node_modules)\//
	};
});
```

**Comment by dylans** [comment]
Here's the error being thrown, https://d.pr/i/11kXj

**Comment by nicknisi** [comment]
Specifically, the error is that `pathUtil.isAbsolute` doesn't exist in 0.10 https://nodejs.org/docs/v0.10.40/api/path.html

**Comment by vladikoff** [comment]
Ah I see, never hit that issue personally, maybe because we don't use `loaderOptions`.
Thanks for providing issue details!
