### ISSUE TITLE
Cannot find module 'dojo/dojo'

### ISSUE THREAD

**Issue by snorripall** [theintern/intern#441]
Description:
I'm trying to run the intern-tutorial against master and 3.0.0-rc.3 but I keep getting Cannot find module 'dojo/dojo'.

Steps to reproduce:
1. Setup intern-tutorial
2. Change dependencies to "intern": "git@github.com:theintern/intern.git#master" 
3. Run: SAUCE_USERNAME=xyz SAUCE_ACCESS_KEY=xyz ./node_modules/.bin/intern-runner config=tests/intern

Expected result:
A test that works.
 
Actual result:
```
SAUCE_USERNAME=xyz SAUCE_ACCESS_KEY=xyz ./node_modules/.bin/intern-runner config=tests/intern

Error: Cannot find module 'dojo/dojo'
  at Function.Module._resolveFilename  <module.js:336:15>
  at Function.require.resolve  <module.js:388:19>
  at <node_modules/intern/lib/executors/PreExecutor.js:404:32>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at PreExecutor.swapLoader  <node_modules/intern/lib/executors/PreExecutor.js:395:11>
  at swapLoader  <node_modules/intern/lib/executors/PreExecutor.js:357:17>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
npm ERR! Test failed.  See above for more details.
```

Intern version:
master or 3.0.0-rc3 running on node 0.12.7

Any additional information:
Same code works on Intern2 running on node 0.10. 

Edit: Update template

**Comment by kitsonk** [comment]
What does your intern configuration look like.  For me, most of the time, you just need to drop out the `useLoader` var from your config for 3.  I don't know if it has been removed from the reference files.

**Comment by snorripall** [comment]
That solved it, thanks :) !
