### ISSUE TITLE
error TS2420 in Tunnel

### ISSUE THREAD

**Issue by anitba** [theintern/intern#999]
Hi, after the update to 4.7 (maybe even before) I get a linter error in my project:

node_modules/@theintern/digdug/Tunnel.d.ts(6,22): error TS2420: Class 'Tunnel' incorrectly implements interface 'Url'. Type 'Tunnel' is missing the following properties from type 'Url': hash, host, href, path, and 3 more.

## Environment

Intern version: 4.7
Node version: 10.15
NPM version: 6.4.1

**Comment by jason0x43** [comment]
Are you using Tunnel explicitly for something? The typing for Url changed in the v12 node typings and Tunnel is no longer conformant, but that shouldn't be an issue writing or running tests.

**Comment by jason0x43** [comment]
This issue was opened a couple of weeks ago at theintern/digdug#78. I'm not sure why it only seems to come up in some cases, but apparently it's not sufficiently resolved. I reopened that, so add any further comments there and watch that one for a resolution.
