### ISSUE TITLE
Test failure after upgrading from 2.2.2 to 3.0.6

### ISSUE THREAD

**Issue by rahulsh1** [theintern/intern#540]
After upgrading to version `3.0.6`, the tests are failing with the error as given:

    [INFO]
    [INFO] Running "jsdoc:dist" (jsdoc) task
    [INFO] Documentation generated to /home2/wsc/wsc/src/product/feature/clientsdk/web/target/js/doc
    [INFO] Running "intern:unitTest" (intern) task
    [INFO] Error: Cannot find module 'dojo/dojo'
    [INFO]   at Function.Module._resolveFilename  <module.js:336:15>
    [INFO]   at Function.require.resolve  <module.js:388:19>
    [INFO]   at <node_modules/intern/lib/executors/PreExecutor.js:437:32>
    [INFO]   at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
    [INFO]   at PreExecutor.swapLoader  <node_modules/intern/lib/executors/PreExecutor.js:428:11>
    [INFO]   at swapLoader  <node_modules/intern/lib/executors/PreExecutor.js:389:17>
    [INFO]   at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
    [INFO]   at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
    [INFO]   at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
    [INFO]   at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
    [INFO] Warning: Test failure; check output above for details. Used --force, continuing.
    [INFO]
    [INFO] Done, but with warnings.
    [INFO]

All my tests worked fine with `2.2.2`
Any suggestions?

**Comment by kitsonk** [comment]
You like just need to remove `useLoader` option in your intern configuration.

**Comment by JSMike** [comment]
Are you trying to use dojo 1 for your loader? what's your config like?

**Comment by csnover** [comment]
Thanks for your interest in Intern!

In order to keep the bug tracker focused only on the development of Intern itself, we ask that people please follow the [contribution guidelines](https://github.com/theintern/intern/blob/master/CONTRIBUTING.md) and not submit questions to the bug tracker. Please read the [Getting Support](https://github.com/theintern/intern/wiki/Support) wiki for information on where to submit questions. Thank you!
